pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
            checkout([$class: 'GitSCM', branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/iamvijayp/terratest.git']]])            

          }
        }
        
        stage ("terraform init") {
            steps {
                dir('iac/terraform/qaframework') {
                sh ('terraform init') 
            }
            }

        }
        
        stage ("terraform Action") {
            steps {
                echo "Terraform action is --> ${action}"
                sh ('terraform ${action} --auto-approve') 
           }
        }
    }
}
