pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
            checkout([$class: 'GitSCM', branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/iamvijayp/terratest.git']]])            

          }
        }
        
        stage ("terraform init") {
            steps {
                dir('iac/terraform/qaframework') {
                sh ('terraform init') 
            }
            }

        }
        
        stage ("terraform Action") {
            steps {

                withCredentials([[
                $class: 'AmazonWebServicesCredentialsBinding',
                credentialsId: "iam_user_vijay",
                accessKeyVariable: 'AWS_ACCESS_KEY_ID',
                secretKeyVariable: 'AWS_SECRET_ACCESS_KEY'
            ]]) 
            {
                dir('iac/terraform/qaframework')
                {
                sh ('terraform apply --auto-approve')
                }
            }    
           }
        }
    }
}
